[variables]
NIXPACKS_JVM_TOOLS = "gradle"

[phases.setup]
nixPkgs = ['openjdk17']

[phases.build]
dependsOn = ['setup']
cmds = [
    'chmod +x gradlew',
    './gradlew clean bootJar -x test --no-daemon'
]

[phases.start]
cmd = 'java -jar build/libs/foodyback.jar'