# Configuration Railway pour Backend et Frontend

# Service Backend
[environments.production.services.backend]
build.workdir = "FoodyBack/org"
build.dockerfile = "../../Dockerfile"

[environments.production.services.backend.variables]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"

# Service Frontend
[environments.production.services.frontend]
build.workdir = "foodyfront"
build.dockerfile = "Dockerfile"

[environments.production.services.frontend.variables]
PORT = "80"
REACT_APP_API_URL = "foodyreserv-backend.up.railway.app"